### ISSUE TITLE
How to set Flagr server endpoint?

### ISSUE THREAD

**Issue by faceleg** [checkr/jsflagr#4]
Following your instructions, I've got the flagr server running on `localhost:18000`. 

This module expects it to be at `http://localhost:80`, and I don't see an obvious way to configure it to use a "custom" endpoint

**Comment by zhouzhuojie** [comment]
Thanks, after some searching, I've got the following working.

```
var Jsflagr = require('jsflagr');
var apiInstance = new Jsflagr.EvaluationApi();
apiInstance.apiClient.basePath = 'http://localhost:18000/api/v1'

...

```
